---

- name: openssh server package
  package:
    name: openssh-server
    state: present

- name: sshd config
  template:
    src: "{{ item }}"
    dest: /etc/ssh/sshd_config
    backup: yes
    validate: sshd -T -f %s
  with_first_found:
    - "{{ playbook_dir }}/templates/{{ cfg }}"
    - sshd_config.j2
  notify: reload sshd
