---

- name: group exists for {{ login }}
  group:
    name: "{{ login }}"
    gid: "{{ uid }}"

- name: user exists for {{ login }}
  user:
    name: "{{ login }}"
    uid: "{{ uid }}"
    group: "{{ login }}"
    createhome: no
    shell: /sbin/nologin

- name: Home directory exists for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}"
    state: directory
    mode: 0750
    owner: root
    group: "{{ login }}"

- name: Transfer Directories exists for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}/{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ login }}"
    group: "{{ login }}"
  with_items: "{{ transfer_dirs }}"
  when: transfer_dirs is defined
    
- name: /etc for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}/etc"
    state: directory
    mode: 0750
    owner: root
    group: "{{ login }}"

- name: /etc/group for {{ login }}
  template:
    dest: "{{ homedir_path }}/{{ login }}/etc/group"
    src: "{{ item }}"
    mode: 0640
    owner: root
    group: "{{ login }}"
    backup: yes
  with_first_found:
    - "{{ playbook_dir }}/templates/chroot-group.j2"
    - etc/group.j2

- name: /etc/passwd for {{ login }}
  template:
    dest: "{{ homedir_path }}/{{ login }}/etc/passwd"
    src: "{{ item }}"
    mode: 0640
    owner: root
    group: "{{ login }}"
    backup: yes
  with_first_found:
    - "{{ playbook_dir }}/templates/chroot-passwd.j2"
    - etc/passwd.j2

- name: .ssh for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}/.ssh"
    state: directory
    owner: root
    group: "{{ login }}"
    mode: 0750
    setype: ssh_home_t

- name: authorized_keys for {{ login }} exists
  copy:
    force: no
    content: ""
    dest: "{{ homedir_path }}/{{ login }}/.ssh/authorized_keys"
    owner: root
    group: "{{ login }}"
    mode: 0640
    setype: ssh_home_t

- name: authorized_keys for {{ login }} has correct permissions
  file:
    path: "{{ homedir_path }}/{{ login }}/.ssh/authorized_keys"
    owner: root
    group: "{{ login }}"
    mode: 0640
    setype: ssh_home_t

- name: authorized_keys for {{ login }}
  authorized_key:
    user: "{{ login }}"
    state: present
    key: "{{ item }}"
    manage_dir: no
  with_items: "{{ authorized_keys }}"
