---

- name: group exists for {{ login }}
  group:
    name: "{{ login }}"
    gid: "{{ uid }}"

- name: user exists for {{ login }}
  user:
    name: "{{ login }}"
    uid: "{{ uid }}"
    group: "{{ login }}"
    createhome: no
    shell: /sbin/nologin

- name: user is member of chroot only group
  when: chroot_group is defined
  user:
    name: "{{ login }}"
    groups:
      - "{{ chroot_group }}"

- name: Home directory exists for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}"
    state: directory
    mode: 0750
    owner: root
    group: "{{ login }}"

- name: Transfer Directories exists for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}/{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ login }}"
    group: "{{ login }}"
  with_items: "{{ transfer_dirs }}"
  when: transfer_dirs is defined
    
- name: /etc for {{ login }}
  file:
    path: "{{ homedir_path }}/{{ login }}/etc"
    state: directory
    mode: 0750
    owner: root
    group: "{{ login }}"

- name: /etc/group for {{ login }}
  template:
    dest: "{{ homedir_path }}/{{ login }}/etc/group"
    src: "{{ item }}"
    mode: 0640
    owner: root
    group: "{{ login }}"
    backup: yes
  with_first_found:
    - "{{ playbook_dir }}/templates/chroot-group.j2"
    - etc/group.j2

- name: /etc/passwd for {{ login }}
  template:
    dest: "{{ homedir_path }}/{{ login }}/etc/passwd"
    src: "{{ item }}"
    mode: 0640
    owner: root
    group: "{{ login }}"
    backup: yes
  with_first_found:
    - "{{ playbook_dir }}/templates/chroot-passwd.j2"
    - etc/passwd.j2
