#! vim: set ft=yaml ts=2:
---

- debug: var=ssh
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - ssh.known_hosts.context in [ "Global", "User" ]

- name: file does exist
  copy:
    content: ""
    dest: "{{ ssh_known_hosts_file|default(ssh.config[ssh.known_hosts.context + 'KnownHostsFile']) }}"
    force: false

- name: get host keys
  with_items: "{{ ssh_pattern }}"
  known_hosts:
    path: "{{ ssh_known_hosts_file|default(ssh.config[ssh.known_hosts.context + 'KnownHostsFile']) }}"
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan ' + item) }}"

- name: remove host keys
  when: ssh_known_hosts_file|default(ssh.config[ssh.known_hosts.context + 'KnownHostsFile'])
  with_items: "{{ ssh_pattern }}"
  lineinfile:
    path: "{{ ssh_known_hosts_file|default(ssh.config[ssh.known_hosts.context + 'KnownHostsFile']) }}"
    regexp: ',{{ item }}|{{ item }},'
    state: absent
